languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon CloudOps Security Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "John Dixon, Rim Zaafouri"
description = "Amazon CloudOps Security Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/dixonaws/aws-cloudops-security/edit/main/content/"
baseURL = "https://dixonaws.com/aws-cloudops-security/index.html"
disableLandingPage=false
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

#

[menu]

[[menu.shortcuts]]
identifier = 'github'
name="<i class='fab fa-github fa-lg'></i> Github Repo"
url = "https://github.com/dixonaws/aws-cloudops-security"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @dixonjp90"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=dixonjp90"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> John Dixon"
identifier = "li0"
url = "https://www.linkedin.com/in/jpd44/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Rim Zaafouri"
identifier = "li1"
url = "https://www.linkedin.com/in/rimzaafouri/"
weight = 40

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]

[markup.goldmark.renderer]
unsafe= true